/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetointegrador;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Porcionato
 */
public class CadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form CadastroImovel1
     */
    public CadastroImovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        input_endereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        input_cidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_estado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        input_area = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_valor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        input_cep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        input_quartos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        input_banheiros = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        input_vagas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        select_tipoImovel = new javax.swing.JComboBox<>();
        select_proprietario = new javax.swing.JComboBox<>();
        btn_limparCampo = new javax.swing.JButton();
        btn_cadastrarImovel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Cadastro de Imovéis");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Endereço :");

        btn_menu.setBackground(new java.awt.Color(153, 0, 0));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("VOLTAR");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        input_endereco.setBackground(new java.awt.Color(204, 204, 204));
        input_endereco.setText("Digite seu endereco aqui...");
        input_endereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_enderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_enderecoFocusLost(evt);
            }
        });
        input_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_enderecoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Cidade :");

        input_cidade.setBackground(new java.awt.Color(204, 204, 204));
        input_cidade.setText("Digite sua cidade aqui...");
        input_cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cidadeFocusLost(evt);
            }
        });
        input_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_cidadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Estado:");

        input_estado.setBackground(new java.awt.Color(204, 204, 204));
        input_estado.setText("Digite seu estado aqui...");
        input_estado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_estadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_estadoFocusLost(evt);
            }
        });
        input_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_estadoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("CEP:");

        input_area.setBackground(new java.awt.Color(204, 204, 204));
        input_area.setText("Digite a area do imovel aqui...");
        input_area.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_areaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_areaFocusLost(evt);
            }
        });
        input_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_areaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Área: ");

        input_valor.setBackground(new java.awt.Color(204, 204, 204));
        input_valor.setText("Digite o valor aqui...");
        input_valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_valorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_valorFocusLost(evt);
            }
        });
        input_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_valorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Valor:");

        input_cep.setBackground(new java.awt.Color(204, 204, 204));
        input_cep.setText("Digite seu CEP aqui...");
        input_cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cepFocusLost(evt);
            }
        });
        input_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_cepActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("--- Quantidade ---");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("Quartos:");

        input_quartos.setBackground(new java.awt.Color(204, 204, 204));
        input_quartos.setText("Digite quantidade de quartos aqui...");
        input_quartos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_quartosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_quartosFocusLost(evt);
            }
        });
        input_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_quartosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Banheiros:");

        input_banheiros.setBackground(new java.awt.Color(204, 204, 204));
        input_banheiros.setText("Digite quantidade de banheiros aqui...");
        input_banheiros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_banheirosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_banheirosFocusLost(evt);
            }
        });
        input_banheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_banheirosActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setText("Vagas:");

        input_vagas.setBackground(new java.awt.Color(204, 204, 204));
        input_vagas.setText("Digite quantidade de vagas aqui...");
        input_vagas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_vagasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_vagasFocusLost(evt);
            }
        });
        input_vagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_vagasActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText("--- Informações ---");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        jLabel17.setText("Tipo Imovél:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setText("Proprietário:");

        select_tipoImovel.setBackground(new java.awt.Color(204, 204, 204));
        select_tipoImovel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        select_tipoImovel.setForeground(new java.awt.Color(153, 0, 0));
        select_tipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Cobertura", "Kitnet", "Loft", "Sobrado", "Studio", "Terreno", "Chácara", "Galpão" }));

        select_proprietario.setBackground(new java.awt.Color(204, 204, 204));
        select_proprietario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        select_proprietario.setForeground(new java.awt.Color(153, 0, 0));
        select_proprietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "José da Silva", "Maria Oliveira", "Paulo Santos", "Carla Martins", "Rafael Gomes", "Letícia Ferreira", "André Almeida", "Beatriz Souza", "Fábio Costa", "Viviane Rocha" }));

        btn_limparCampo.setBackground(new java.awt.Color(102, 102, 102));
        btn_limparCampo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_limparCampo.setForeground(new java.awt.Color(255, 255, 255));
        btn_limparCampo.setText("CANCELAR");
        btn_limparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparCampoActionPerformed(evt);
            }
        });

        btn_cadastrarImovel.setBackground(new java.awt.Color(153, 0, 0));
        btn_cadastrarImovel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cadastrarImovel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarImovel.setText("CADASTRAR");
        btn_cadastrarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarImovelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_endereco))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_estado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_valor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_area))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_banheiros, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_quartos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(select_proprietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(select_tipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cadastrarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_limparCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_menu))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(input_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(input_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(input_quartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(input_banheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(select_tipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(select_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(input_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limparCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Imovéis Cadastrados");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_enderecoActionPerformed

    private void input_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_cidadeActionPerformed

    private void input_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_estadoActionPerformed

    private void input_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_areaActionPerformed

    private void input_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_valorActionPerformed

    private void input_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_cepActionPerformed

    private void input_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_quartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_quartosActionPerformed

    private void input_banheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_banheirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_banheirosActionPerformed

    private void input_vagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_vagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_vagasActionPerformed

    private void btn_limparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparCampoActionPerformed
        // TODO add your handling code here:
        input_endereco.setText("");
        input_cidade.setText("");
        input_estado.setText("");
        input_cep.setText("");
        input_valor.setText("");
        input_area.setText("");
        input_quartos.setText("");
        input_banheiros.setText("");
        input_vagas.setText("");
        select_tipoImovel.setSelectedIndex(0);
        select_proprietario.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limparCampoActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        dispose();
        new MenuOptions().setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void input_enderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_enderecoFocusGained
        // TODO add your handling code here:
        if (input_endereco.getText().equals("Digite seu endereco aqui...")) {
            input_endereco.setText("");
        }
    }//GEN-LAST:event_input_enderecoFocusGained

    private void input_enderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_enderecoFocusLost
        // TODO add your handling code here:
        if (input_endereco.getText().equals("")) {
            input_endereco.setText("Digite seu endereco aqui...");
        }
    }//GEN-LAST:event_input_enderecoFocusLost

    private void input_cidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cidadeFocusGained
        // TODO add your handling code here:
        if (input_cidade.getText().equals("Digite sua cidade aqui...")) {
            input_cidade.setText("");
        }
    }//GEN-LAST:event_input_cidadeFocusGained

    private void input_cidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cidadeFocusLost
        // TODO add your handling code here:
        if (input_cidade.getText().equals("")) {
            input_cidade.setText("Digite sua cidade aqui...");
        }
    }//GEN-LAST:event_input_cidadeFocusLost

    private void input_estadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_estadoFocusGained
        // TODO add your handling code here:
        if (input_estado.getText().equals("Digite seu estado aqui...")) {
            input_estado.setText("");
        }
    }//GEN-LAST:event_input_estadoFocusGained

    private void input_estadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_estadoFocusLost
        // TODO add your handling code here:
        if (input_estado.getText().equals("")) {
            input_estado.setText("Digite seu estado aqui...");
        }
    }//GEN-LAST:event_input_estadoFocusLost

    private void input_cepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cepFocusGained
        // TODO add your handling code here:
        if (input_cep.getText().equals("Digite seu CEP aqui...")) {
            input_cep.setText("");
        }
    }//GEN-LAST:event_input_cepFocusGained

    private void input_cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cepFocusLost
        // TODO add your handling code here:
        if (input_cep.getText().equals("")) {
            input_cep.setText("Digite seu CEP aqui...");
        }
    }//GEN-LAST:event_input_cepFocusLost

    private void input_valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_valorFocusGained
        // TODO add your handling code here:
        if (input_valor.getText().equals("Digite o valor aqui...")) {
            input_valor.setText("");
        }
    }//GEN-LAST:event_input_valorFocusGained

    private void input_valorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_valorFocusLost
        // TODO add your handling code here:
        if (input_valor.getText().equals("")) {
            input_valor.setText("Digite o valor aqui...");
        }
    }//GEN-LAST:event_input_valorFocusLost

    private void input_areaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_areaFocusGained
        // TODO add your handling code here:
        if (input_area.getText().equals("Digite a area do imovel aqui...")) {
            input_area.setText("");
        }
    }//GEN-LAST:event_input_areaFocusGained

    private void input_areaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_areaFocusLost
        // TODO add your handling code here:
        if (input_area.getText().equals("")) {
            input_area.setText("Digite a area do imovel aqui...");
        }
    }//GEN-LAST:event_input_areaFocusLost

    private void input_quartosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_quartosFocusGained
        // TODO add your handling code here:
        if (input_quartos.getText().equals("Digite quantidade de quartos aqui...")) {
            input_quartos.setText("");
        }
    }//GEN-LAST:event_input_quartosFocusGained

    private void input_quartosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_quartosFocusLost
        // TODO add your handling code here:
        if (input_quartos.getText().equals("")) {
            input_quartos.setText("Digite quantidade de quartos aqui...");
        }
    }//GEN-LAST:event_input_quartosFocusLost

    private void input_banheirosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_banheirosFocusGained
        // TODO add your handling code here:
        if (input_banheiros.getText().equals("Digite quantidade de banheiros aqui...")) {
            input_banheiros.setText("");
        }
    }//GEN-LAST:event_input_banheirosFocusGained

    private void input_banheirosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_banheirosFocusLost
        // TODO add your handling code here:
        if (input_banheiros.getText().equals("")) {
            input_banheiros.setText("Digite quantidade de banheiros aqui...");
        }
    }//GEN-LAST:event_input_banheirosFocusLost

    private void input_vagasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_vagasFocusGained
        // TODO add your handling code here:
        if (input_vagas.getText().equals("Digite quantidade de vagas aqui...")) {
            input_vagas.setText("");
        }
    }//GEN-LAST:event_input_vagasFocusGained

    private void input_vagasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_vagasFocusLost
        // TODO add your handling code here:
        if (input_vagas.getText().equals("")) {
            input_vagas.setText("Digite quantidade de vagas aqui...");
        }
    }//GEN-LAST:event_input_vagasFocusLost

    private void btn_cadastrarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarImovelActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Deseja realemente cadastrar Imovel ?", "opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        // yes = 0; no = 1; cancel = 2;
        if (valor == 0) {
            Imovel i = new Imovel();
            i.setEndereco(input_endereco.getText());
            i.setCidade(input_cidade.getText());
            i.setEstado(input_estado.getText());
            i.setCep(input_cep.getText());
            i.setValor(input_valor.getText());
            i.setArea(input_area.getText());
            i.setQuartos(input_quartos.getText());
            i.setBanheiros(input_banheiros.getText());
            i.setVagas(input_vagas.getText());
            i.setTipoImovel((String) select_tipoImovel.getSelectedItem());
            i.setProprietario((String) select_proprietario.getSelectedItem());
            
            area.setText(i.toString());
        }
    }//GEN-LAST:event_btn_cadastrarImovelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroImovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_cadastrarImovel;
    private javax.swing.JButton btn_limparCampo;
    private javax.swing.JButton btn_menu;
    private javax.swing.JTextField input_area;
    private javax.swing.JTextField input_banheiros;
    private javax.swing.JTextField input_cep;
    private javax.swing.JTextField input_cidade;
    private javax.swing.JTextField input_endereco;
    private javax.swing.JTextField input_estado;
    private javax.swing.JTextField input_quartos;
    private javax.swing.JTextField input_vagas;
    private javax.swing.JTextField input_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> select_proprietario;
    private javax.swing.JComboBox<String> select_tipoImovel;
    // End of variables declaration//GEN-END:variables
}
